export const CAR_ACTION_TYPES = {
    ADD_CAR_START: "ADD_CAR_START",
    ADD_CAR_SUCCESS: "ADD_CAR_SUCCESS",
    ADD_CAR_FAILED: "ADD_CAR_FAILED",

    UPDATE_CAR_START: "UPDATE_CAR_START",
    UPDATE_CAR_SUCCESS: "UPDATE_CAR_SUCCESS",
    UPDATE_CAR_FAILED: "UPDATE_CAR_FAILED",
}