export const RESERVATION_ACTION_TYPES = {
  ADD_RESERVATION: "ADD_RESERVATION",

  GET_RESERVATIONS_START: "GET_RESERVATIONS_START",
  GET_RESERVATIONS_SUCCESS: "GET_RESERVATIONS_SUCCESS",
  GET_RESERVATIONS_FAILED: "GET_RESERVATIONS_FAILED",

  ADD_RESERVATIONS_START: "ADD_RESERVATIONS_START",
  ADD_RESERVATIONS_SUCCESS: "ADD_RESERVATIONS_SUCCESS",
  ADD_RESERVATIONS_FAILED: "ADD_RESERVATIONS_FAILED",

  DELETE_RESERVATION_START: "DELETE_RESERVATION_START",
  DELETE_RESERVATION_SUCCESS: "DELETE_RESERVATION_SUCCESS",
  DELETE_RESERVATION_FAILED: "DELETE_RESERVATION_FAILED",
};
