export const INFRASTRUCTURE_ACTION_TYPES = {
    GET_INFRASTRUCTURE_DATA_START: "GET_INFRASTRUCTURE_DATA_START",
    GET_INFRASTRUCTURE_DATA_SUCCESS: "GET_INFRASTRUCTURE_DATA_SUCCESS",
    GET_INFRASTRUCTURE_DATA_FAILED: "GET_INFRASTRUCTURE_DATA_FAILED",

    ADD_INFRASTRUCTURE_DATA_START: "ADD_INFRASTRUCTURE_DATA_START",
    ADD_INFRASTRUCTURE_DATA_SUCCESS: "ADD_INFRASTRUCTURE_DATA_SUCCESS",
    ADD_INFRASTRUCTURE_DATA_FAILED: "ADD_INFRASTRUCTURE_DATA_FAILED",

    UPDATE_INFRASTRUCTURE_DATA_START: "UPDATE_INFRASTRUCTURE_DATA_START",
    UPDATE_INFRASTRUCTURE_DATA_SUCCESS: "UPDATE_INFRASTRUCTURE_DATA_SUCCESS",
    UPDATE_INFRASTRUCTURE_DATA_FAILED: "UPDATE_INFRASTRUCTURE_DATA_FAILED",

    SET_INFRASTRUCTURE_DATA: "SET_INFRASTRUCTURE_DATA",

    SET_NUMBER_OF_BADGES: "SET_NUMBER_OF_BADGES",

    SET_CHOSEN_ELEMENT: "SET_CHOSEN_ELEMENT",

    SET_IS_SUCCESSFUL: "SET_IS_SUCCESSFUL",
    
    SET_SHOW_DISCOUNT: "SET_SHOW_DISCOUNT"
}