export const CONFIGURATION_ACTION_TYPES = {
    SET_START_TIME: "SET_START_TIME",
    CALCULATE_READY_TIME_START: "CALCULATE_READY_TIME_START",
    CALCULATE_READY_TIME_SUCCESS: "CALCULATE_READY_TIME_SUCCESS",
    CALCULATE_READY_TIME_FAILED: "CALCULATE_READY_TIME_FAILED",
}