export const CONFIGURATION_ACTION_TYPES = {
    SET_PLUG_IN: "SET_PLUG_IN",
    CALCULATE_READY_TIME_START: "CALCULATE_READY_TIME_START",
    CALCULATE_READY_TIME_SUCCESS: "CALCULATE_READY_TIME_SUCCESS",
    CALCULATE_READY_TIME_FAILED: "CALCULATE_READY_TIME_FAILED",
}