export const CONFIGURATION_ACTION_TYPES = {
    SET_START_TIME: "SET_START_TIME",
    CALCULATE_CARS_DATA_START: "CALCULATE_CARS_DATA_START",
    CALCULATE_CARS_DATA_SUCCESS: "CALCULATE_CARS_DATA_SUCCESS",
    CALCULATE_CARS_DATA_FAILED: "CALCULATE_CARS_DATA_FAILED",
}