export const WALLBOX_ACTION_TYPES = {
    ADD_WALLBOX_START: "ADD_WALLBOX_START",
    ADD_WALLBOX_SUCCESS: "ADD_WALLBOX_SUCCESS",
    ADD_WALLBOX_FAILED: "ADD_WALLBOX_FAILED",

    UPDATE_WALLBOX_START: "UPDATE_WALLBOX_START",
    UPDATE_WALLBOX_SUCCESS: "UPDATE_WALLBOX_SUCCESS",
    UPDATE_WALLBOX_FAILED: "UPDATE_WALLBOX_FAILED",
}